application: myschooldirectory
version: gitmd5hash
runtime: python27
api_version: 1
threadsafe: yes

includes:
- bootstrap.yaml
- api.yaml
- ui.yaml

libraries:
- name: webapp2
  version: "2.5.1"

- name: pycrypto
  version: "2.6"

